name: Engineering Docs CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"

      - name: Install
        run: yarn install

      - name: Install markdownlinter-cli
        run: npm install markdownlint-cli

      - name: Lint all markdown files
        run: ./node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5
