name: Engineering Docs CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"

      - name: Install
        run: yarn install

      - name: Lint markdown
        run: yarn mdlint
